export enum ECategoryName {
  SOCIAL = 'social',
  AUDIT = 'audit',
  RWA = 'rwa',
  LAUNCHPADS = 'launchpads',
  SHOPPING = 'shopping',
  DEV_TOOLS = 'dev_tools',
  NFT_SERVICES = 'nft_services',
  GAMES = 'games',
  EXCHANGE_DEX = 'exchanges_dex',
  GAMBLING = 'gambling',
  EXCHANGE = 'exchange',
  CHATS = 'chats',
  NFT_COLLECTION = 'nft_collections',
  CHANNELS = 'channels',
  VPN = 'vpn',
  UTILITIES = 'utilities',
  BRIDGES = 'brigdes',
  EXPLORERS = 'explorers',
  WALLETS = 'wallets',
  STAKING = 'staking',
}
